const GECKO_FACTS: string[] = [
  "Sticky feet are self-cleaning",
  "Geckos inspire NASA microgravity technology #LizardsinStem",
  "Geckos see colour at night",
  "Geckos can walk on water #AndOnThethirdDayHeRoseAgain",
  "Geckos can't stick to Teflon #SponsoredbyTefal",
  "It is not known whether geckos enjoy sports.",
  "Geckos have between 100 and 300 teeth. Being their tooth fairy is no joke",
  "Geckos have not yet secured the right to vote #FightThePower",
  "It takes around 30 days to grow a new tail",
  "Some gecko species are all female #SistersAreDoingItForThemselves",
  "The mourning gecko reproduces by cloning herself #SheDontNeedNoMan #ShakeWhatYourMamaGaveYa",
  "Geckos support world domination. They've colonised every continent except Antarctica",
  "Geckos have an endocannabinoid system #LegaliseIt",
  "Hot eggs = angry lizards",
  "Not all geckos have legs (but they ain't snakes)",
  "Geckos have ancient wisdom. They've witnessed the extinction of dinosaurs and Caesar's invasion of Britain",
  "Geckos are the only lizards that vocalise #StepAsideAretha",
  "Rock 'n Roll Mondo Gecko was a peace-lovin' lounge lizard whose battle bass guitar gets 30 miles to the chord #TMNT",
  'In Japanese culture, geckos ("yamori") are regarded as protectors against bad luck and evil spirits',
  "Never harm a gecko. You'll get seven years of bad luck, the good things in your past #VerySupersitious",
  "Geckos have been involuntarily launched into orbit #GoGetThoseGeckos",
  "If a leaf-tailed gecko screams at you, you MUST scream back!",
  "Geckos eat their own skin (and enjoy it)",
  'In ancient Egyptian culture, the lizard represented keen-mindedness and luck. The hieroglyph of the lizard translates as "plentiful."',
  "Shamans say geckos are dream keepers who whisper esoteric secrets to fortunate humans while they sleep #FingersAndToesCrossed",
];

export default GECKO_FACTS;
